### ISSUE TITLE
Compressor Recipe only takes galacticraft aluminum

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Astroblock2#4]
For example, doesn't take Thermal Foundation Aluminum made with the Redstone Furnace

**Comment by knoxhack** [comment]
Fixed in 0.4.2

**Comment by mtbrenner** [comment]
![image](https://user-images.githubusercontent.com/4916644/90724418-d1d0b100-e2be-11ea-98ae-e0da730b23b9.png)
Still an issue, this is the recipe which only takes Galacticraft aluminum ingots
